all:
	gcc simple-thread-timer.c -o simple-thread-timer -lpthread
	gcc simple-thread.c -o simple-thread -lpthread
	gcc simple-thread-benchmark.c -o simple-thread-benchmark -lpthread
clean:
	rm -rf simple-thread-timer
	rm -rf simple-thread
	rm -rf simple-thread-benchmark
