all:
	gcc simple-fork.c -o simple-fork
	gcc simple-shell.c -o simple-shell
	gcc simple-shared.c -o simple-shared
	gcc failing.c -o failing
	gcc waitp-example.c -o waitp-example

clean: 
	rm -rf simple-fork
	rm -rf simple-shell
	rm -rf simple-shared
	rm -rf failing
	rm -rf waitp-example
